server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  application:
    name: insup-application
  
  profiles:
    active: prod
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
    default-property-inclusion: non_null
  
  web:
    resources:
      add-mappings: true

logging:
  level:
    com.incomm.insup: INFO
    org.springframework: WARN
    org.hibernate: WARN
    org.apache: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ./logs/application.log
    max-size: 100MB
    max-history: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  health:
    defaults:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: dev
  
server:
  port: 8080

logging:
  level:
    com.incomm.insup: DEBUG
    org.springframework: INFO

# TCP 서버 설정 (sipsvc와의 통신)
tcp:
  server:
    port: 9090
    boss-threads: 1
    worker-threads: 4
    so-backlog: 128
    so-keepalive: true
    tcp-nodelay: true
    connection-timeout: 7200000  # 2시간 (밀리초)
    max-connections: 100
    
# INSUPC 클라이언트 설정
insupc:
  clients:
    - name: "INSUPC-1"
      host: "127.0.0.1"
      port: 19000
      connection-pool-size: 5
      connection-timeout: 30000
      read-timeout: 10000
      retry-count: 3
      retry-interval: 5000

# 워커 스레드 설정
worker:
  thread-pool-size: 8
  queue-capacity: 1000
  keep-alive-time: 60
  thread-name-prefix: "worker-"

# 인증 및 보안 설정
security:
  allowed-clients:
    - ip: "127.0.0.1"
      mac: "00:00:00:00:00:01"
      auth-key: "TEST_AUTH_KEY_001"
      description: "Test Client 1"

---
spring:
  config:
    activate:
      on-profile: prod
  
server:
  port: 8080

logging:
  level:
    com.incomm.insup: INFO
    root: WARN

# TCP 서버 설정 (sipsvc와의 통신)
tcp:
  server:
    port: 9090
    boss-threads: 1
    worker-threads: 4
    so-backlog: 128
    so-keepalive: true
    tcp-nodelay: true
    connection-timeout: 7200000  # 2시간 (밀리초)
    max-connections: 100
    
# INSUPC 클라이언트 설정
insupc:
  clients:
    - name: "INSUPC-1"
      host: "127.0.0.1"
      port: 19000
      connection-pool-size: 5
      connection-timeout: 30000
      read-timeout: 10000
      retry-count: 3
      retry-interval: 5000

# 워커 스레드 설정
worker:
  thread-pool-size: 8
  queue-capacity: 1000
  keep-alive-time: 60
  thread-name-prefix: "worker-"

# 인증 및 보안 설정
security:
  allowed-clients:
    - ip: "127.0.0.1"
      mac: "00:00:00:00:00:01"
      auth-key: "TEST_AUTH_KEY_001"
      description: "Test Client 1"