spring:
  profiles:
    active: test
  application:
    name: incomm-insup

# 공통 설정
server:
  port: 8080
  servlet:
    context-path: /api
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized

logging:
  config: classpath:logback-spring.xml