# Test 환경 설정
server:
  port: 8080

# TCP 서버 설정 (sipsvc와의 통신)
tcp:
  server:
    port: 9090
    boss-threads: 1
    worker-threads: 4
    so-backlog: 128
    so-keepalive: true
    tcp-nodelay: true
    connection-timeout: 7200000  # 2시간 (밀리초)
    max-connections: 100
    
# INSUPC 클라이언트 설정
insupc:
  clients:
    - name: "INSUPC-1"
      host: "127.0.0.1"
      port: 19000
      connection-pool-size: 5
      connection-timeout: 30000
      read-timeout: 10000
      retry-count: 3
      retry-interval: 5000
    - name: "INSUPC-2"
      host: "127.0.0.1"
      port: 19001
      connection-pool-size: 3
      connection-timeout: 30000
      read-timeout: 10000
      retry-count: 3
      retry-interval: 5000

# 워커 스레드 설정
worker:
  thread-pool-size: 8
  queue-capacity: 1000
  keep-alive-time: 60
  thread-name-prefix: "worker-"

# 인증 및 보안 설정
security:
  allowed-clients:
    - ip: "127.0.0.1"
      mac: "00:00:00:00:00:01"
      auth-key: "TEST_AUTH_KEY_001"
      description: "Test Client 1"
    - ip: "192.168.1.100"
      mac: "00:11:22:33:44:55"
      auth-key: "PROD_AUTH_KEY_001"
      description: "Production sipsvc 1"
    - ip: "192.168.1.101"
      mac: "00:11:22:33:44:56"
      auth-key: "PROD_AUTH_KEY_002"
      description: "Production sipsvc 2"

# 메시지 처리 설정
message:
  max-size: 8192  # 최대 메시지 크기 (bytes)
  encoding: "UTF-8"
  timeout: 30000  # 메시지 처리 타임아웃 (밀리초)

# JVM 설정
jvm:
  heap-size: "1024m"
  gc-type: "G1GC"